baseurl = "https://rolo.tips/"
title = "Mi página matona"
languageCode = "es"
paginate = "5" # Number of posts per page
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author]
  name = "Rolando Flores"
  bio = "Aquí se supone pongo mi bio"
  avatar = "img/avatar.png"

[Params]
  subtitle = "En Cabeza Ajena" # Subtitle of your site
  description = "Salvo que quieras encontrar atajo" # Description of your site
  opengraph = false
  twitter_cards = false
  readmore = false # Show "Read more" button in list if true
  authorbox = true
  post_navigation = true
  post_meta = ["date", "categories"] # Order of post meta information

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
